---
provider:
  type: aws
  region: us-east-2
  profile: lab
vpc:
  # https://www.davidc.net/sites/default/subnets/subnets.html?network=10.0.0.0&mask=16&division=15.7231
  cidr: 10.0.0.0/16
  ipv6_enabled: true
  enable_flow_log: true
  acls:
    public:
      inbound: []
      outbound:
        default:
          rule_number: 100
          rule_action: "allow"
          from_port: 0
          to_port: 0
          protocol: "-1"
          cidr_block: "0.0.0.0/0"
    private:
      inbound: []
      outbound:
        default:
          rule_number: 100
          rule_action: "allow"
          from_port: 0
          to_port: 0
          protocol: "-1"
          cidr_block: "0.0.0.0/0"
    database:
      inbound: []
      outbound:
        default:
          rule_number: 100
          rule_action: "allow"
          from_port: 0
          to_port: 0
          protocol: "-1"
          cidr_block: "0.0.0.0/0"
    intra:
      inbound: []
      outbound:
        default:
          rule_number: 100
          rule_action: "allow"
          from_port: 0
          to_port: 0
          protocol: "-1"
          cidr_block: "0.0.0.0/0"
  private_subnets:
    - 10.0.0.0/20
    - 10.0.16.0/20
    - 10.0.32.0/20
  public_subnets:
    - 10.0.48.0/20
    - 10.0.64.0/20
    - 10.0.80.0/20
  database_subnets:
    - 10.0.96.0/20
    - 10.0.112.0/20
    - 10.0.128.0/20
  kubernetes_subnets:
    - 10.0.144.0/20
    - 10.0.160.0/20
    - 10.0.176.0/20
  free_subnets:
    - 10.0.192.0/20
    - 10.0.208.0/20
    - 10.0.224.0/20
    - 10.0.240.0/20
kubernetes:
  ami_type: AL2023_x86_64_STANDARD
  # warning 1.30 as a bare string is 1.3 as a value in terraform - yaml conversion maybe?
  version: "1.30"
  instance_types:
    # https://aws.amazon.com/ec2/instance-types/
    - t3.small
    - t3.medium
  default_node_group:
    min_size: 1
    max_size: 3
    desired_size: 1
  node_groups:
